### ISSUE TITLE
Directory naming issue?  "massive-sdk"

### ISSUE THREAD

**Issue by Humancell** [twilio/Breakout_Massive_SDK_Arduino#18]
Hello,

I'm attempting to use this new SDK, and do some testing for you, and ran into my first issue.

```
Multiple libraries were found for "BreakoutSDK.h"
In file included from C:\Users\HUMANC~1\AppData\Local\Temp\arduino_build_721026\sketch\modem.h:3:0,

 Used: C:\Users\Humancell\Documents\Arduino\libraries\Breakout_Massive_SDK_Arduino
 Not used: C:\Users\Humancell\Documents\Arduino\libraries\Breakout_Arduino_Library
 Not used: C:\Users\Humancell\Documents\Arduino\libraries\Breakout_Arduino_Library
                 from C:\Users\Humancell\Documents\Arduino\libraries\Breakout_Massive_SDK_Arduino\examples\AlfaKit\Sample\Sample.ino:8:

 Not used: C:\Users\Humancell\Documents\Arduino\libraries\Breakout_Arduino_Library
C:\Users\Humancell\Documents\Arduino\libraries\Breakout_Massive_SDK_Arduino\src/BreakoutSDK.h:25:41: fatal error: massive-sdk/src/modem/enums.h: No such file or directory

 Not used: C:\Users\Humancell\Documents\Arduino\libraries\Breakout_Arduino_Library
 #include "massive-sdk/src/modem/enums.h"
                                          ^
compilation terminated.
```
Looking in the repo, and my downloaded library .zip, it appears that when downloading the zip the entire "massive-sdk" folder/directory is empty.  I'm not sure why Github didn't include anything it in ... but no files.

Looking at Github in the browser, the directory is shown as:  "massive-sdk @ 4a98ca3" and so it's not being included in the download?

**Comment by Humancell** [comment]
I did follow the link above, (https://github.com/twilio/Breakout_Massive_SDK/tree/4a98ca34c94f04d454f6dd2aa350d26caed853f8) and downloaded the .zip from that location and added the files into the "massive-sdk" empty directory and got past this issue.

I also then hit the issues with ArduinoMQTT and Seeed/Grove Temp/Humidity sensor libraries not being present. 
 Installing them now.

Also ... I know you are jamming for Signal ... please let me know if I can assit you in testing/documenting issues that I am finding?

**Comment by Humancell** [comment]
Last update on this issue ... after performing the steps above, the code compiled and loaded onto my Seeed board just fine!  But it won't connect to the T-Mobile network with an active SIM ...  :-(

**Comment by rbeiter** [comment]
Hi @Humancell - we're working on getting the docs updated on how to install the library and a release build is coming today.  Since we are using a submodule for the shared module code now, downloading from github as a zip isn't quite enough anymore.  I'm glad you are unblocked and will close this issue and work with you on the other issue regarding connectivity.

**Comment by Humancell** [comment]
Thanks!  Let me know how I can assist in testing the docs, process, etc.
